
import java.awt.event.KeyEvent;
public class frame01 extends javax.swing.JFrame {
double n1;
double n2;
double result;
private Object math;
String opr;
String answer;
    private int a;


    /**
     * Creates new form frame01
     */
    public frame01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        textbox = new javax.swing.JTextField();
        off = new javax.swing.JRadioButton();
        on = new javax.swing.JRadioButton();
        btnclear = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        bdecimal = new javax.swing.JButton();
        bsix = new javax.swing.JButton();
        btwo = new javax.swing.JButton();
        bfive = new javax.swing.JButton();
        bfour = new javax.swing.JButton();
        btnoneby = new javax.swing.JButton();
        btnequals = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btntangent = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btnx3 = new javax.swing.JButton();
        btnexpo = new javax.swing.JButton();
        btnsine = new javax.swing.JButton();
        btncosine = new javax.swing.JButton();
        btnxy = new javax.swing.JButton();
        btnfactorial = new javax.swing.JButton();
        bnine = new javax.swing.JButton();
        btnmul = new javax.swing.JButton();
        bthree = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        bone = new javax.swing.JButton();
        beight = new javax.swing.JButton();
        bzero = new javax.swing.JButton();
        bseven = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton32.setText("/");

        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton34.setText("-");

        jButton33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton33.setText("*");

        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton35.setText("+");

        jButton30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton30.setText("9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        textbox.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        textbox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxActionPerformed(evt);
            }
        });

        off.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        off.setText("OFF");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        on.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        on.setText("ON");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnmod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnmod.setText("%");
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });

        bdecimal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bdecimal.setText(".");
        bdecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdecimalActionPerformed(evt);
            }
        });

        bsix.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bsix.setText("6");
        bsix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsixActionPerformed(evt);
            }
        });

        btwo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btwo.setText("2");
        btwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btwoActionPerformed(evt);
            }
        });

        bfive.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bfive.setText("5");
        bfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfiveActionPerformed(evt);
            }
        });

        bfour.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bfour.setText("4");
        bfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfourActionPerformed(evt);
            }
        });

        btnoneby.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnoneby.setText("1/x");
        btnoneby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnonebyActionPerformed(evt);
            }
        });

        btnequals.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnequals.setText("=");
        btnequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalsActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsub.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsub.setText("-");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        btntangent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntangent.setText("tan");
        btntangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntangentActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnx2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnx2.setText("x^2");
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });

        btnx3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnx3.setText("x^3");
        btnx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx3ActionPerformed(evt);
            }
        });

        btnexpo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnexpo.setText("sqrt");
        btnexpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpoActionPerformed(evt);
            }
        });

        btnsine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsine.setText("sin");
        btnsine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsineActionPerformed(evt);
            }
        });

        btncosine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncosine.setText("cos");
        btncosine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosineActionPerformed(evt);
            }
        });

        btnxy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnxy.setText("x^y");
        btnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxyActionPerformed(evt);
            }
        });

        btnfactorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnfactorial.setText("x!");
        btnfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfactorialActionPerformed(evt);
            }
        });

        bnine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bnine.setText("9");
        bnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnineActionPerformed(evt);
            }
        });

        btnmul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnmul.setText("*");
        btnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmulActionPerformed(evt);
            }
        });

        bthree.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bthree.setText("3");
        bthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthreeActionPerformed(evt);
            }
        });

        btndiv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndiv.setText("/");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });

        bone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bone.setText("1");
        bone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boneActionPerformed(evt);
            }
        });

        beight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        beight.setText("8");
        beight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beightActionPerformed(evt);
            }
        });

        bzero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bzero.setText("0");
        bzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bzeroActionPerformed(evt);
            }
        });

        bseven.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bseven.setText("7");
        bseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsevenActionPerformed(evt);
            }
        });

        btnlog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlog.setText("log");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(btnexpo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(btnsine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(on, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addComponent(btncosine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btntangent, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnx2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnx3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnxy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnfactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bfour, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bfive, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bsix, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bone, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btwo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bthree, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bseven, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(beight, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bnine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bzero, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnoneby, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(on, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexpo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncosine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntangent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnx2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnx3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxy, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bseven, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bfour, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bfive, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsix, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btwo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bthree, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bzero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnoneby, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offActionPerformed

@SuppressWarnings("empty-statement")
    private void btnequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalsActionPerformed
         
       
        n2 = Double.parseDouble(textbox.getText());
        if(opr == "+")
        {
            result = n1 + n2;
            textbox.setText(Double.toString(result));
        }
        else if(opr == "-")
        {
            result = n1 - n2;
            textbox.setText(Double.toString(result));
        }
        else if(opr == "*")
        {
            result = n1 * n2;
            textbox.setText(Double.toString(result));
        }
        else if(opr == "/")
        {
            result = n1 / n2;
            textbox.setText(Double.toString(result));
        }
        else if(opr == "%")
        {
            result = n1 % n2;
            textbox.setText(Double.toString(result));
        }
        else if(opr == "x^y")
        {
            for(int i = 0; i<n2; i++)
            {
             result = n1*n2;   
            }
            textbox.setText(Double.toString(result));
    }//GEN-LAST:event_btnequalsActionPerformed
    }
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        String bs = null;
        if(textbox.getText().length() > 0)
        {
            StringBuilder s = new StringBuilder(textbox.getText());
            s.deleteCharAt(textbox.getText().length() - 1);
            bs = s.toString();
            textbox.setText(bs);
            
        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void bthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthreeActionPerformed
        textbox.setText(textbox.getText() + "3");
    }//GEN-LAST:event_bthreeActionPerformed

    private void btnonebyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnonebyActionPerformed
        double t=1/ (Double.parseDouble(textbox.getText()));
        textbox.setText("");
        textbox.setText(textbox.getText() + t);
    }//GEN-LAST:event_btnonebyActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
       double opr = Double.parseDouble(String.valueOf(textbox.getText()));
      opr= Math.log(opr);
      textbox.setText(String.valueOf(opr));
    }//GEN-LAST:event_btnlogActionPerformed

    private void btntangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntangentActionPerformed
        double opr = Double.parseDouble(String.valueOf(textbox.getText()));
      opr= Math.tan(opr);
      textbox.setText(String.valueOf(opr));
    }//GEN-LAST:event_btntangentActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        
        n1 = Double.parseDouble(textbox.getText());
        textbox.setText("");
        opr = ("+");
    }//GEN-LAST:event_btnaddActionPerformed

    private void bzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bzeroActionPerformed
    textbox.setText(textbox.getText() + "0");
    }//GEN-LAST:event_bzeroActionPerformed

    private void boneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boneActionPerformed
    textbox.setText(textbox.getText() + "1");
    }//GEN-LAST:event_boneActionPerformed

    private void btwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btwoActionPerformed
    textbox.setText(textbox.getText() + "2");
    }//GEN-LAST:event_btwoActionPerformed

    private void bfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfourActionPerformed
    textbox.setText(textbox.getText() + "4");
    }//GEN-LAST:event_bfourActionPerformed

    private void bfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfiveActionPerformed
    textbox.setText(textbox.getText() + "5");
    }//GEN-LAST:event_bfiveActionPerformed

    private void bsixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsixActionPerformed
    textbox.setText(textbox.getText() + "6");
    }//GEN-LAST:event_bsixActionPerformed

    private void bsevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsevenActionPerformed
    textbox.setText(textbox.getText() + "7");
    }//GEN-LAST:event_bsevenActionPerformed

    private void beightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beightActionPerformed
    textbox.setText(textbox.getText() + "8");
    }//GEN-LAST:event_beightActionPerformed

    private void bnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnineActionPerformed
    textbox.setText(textbox.getText() + "9");
    }//GEN-LAST:event_bnineActionPerformed

    private void bdecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdecimalActionPerformed
    textbox.setText(textbox.getText() + ".");
    }//GEN-LAST:event_bdecimalActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
    textbox.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        n1 = Double.parseDouble(textbox.getText());
        textbox.setText("");
        opr =("-");
    }//GEN-LAST:event_btnsubActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        n1 = Double.parseDouble(textbox.getText());
        textbox.setText("");
        opr =("/");
    }//GEN-LAST:event_btndivActionPerformed

    private void btnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmulActionPerformed
        n1 = Double.parseDouble(textbox.getText());
        textbox.setText("");
        opr =("*");
    }//GEN-LAST:event_btnmulActionPerformed

    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        n1 = Double.parseDouble(textbox.getText());
        textbox.setText("");
        opr =("%");
    }//GEN-LAST:event_btnmodActionPerformed

    private void btnsineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsineActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.sin(ops);
        textbox. setText(String.valueOf(ops));
       
    }//GEN-LAST:event_btnsineActionPerformed

    private void btncosineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosineActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.cos(ops);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btncosineActionPerformed

    private void btnexpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpoActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.sqrt(ops);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnexpoActionPerformed

    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        double t= (Double.parseDouble(textbox.getText()));
        
        t=t*t;
        textbox.setText("");
        textbox.setText(textbox.getText() + t);
        
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btnx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx3ActionPerformed
        double t= (Double.parseDouble(textbox.getText()));
        
        t=t*t*t;
        textbox.setText("");
        textbox.setText(textbox.getText() + t);
    }//GEN-LAST:event_btnx3ActionPerformed

    private void btnxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxyActionPerformed
         
        n1 = Double.parseDouble(textbox.getText());
        textbox.setText("");
        opr = ("x^y");
    }//GEN-LAST:event_btnxyActionPerformed

    private void btnfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfactorialActionPerformed
        double t= (Double.parseDouble(textbox.getText()));

     double fact = 1;

        for(int i=1;i<=n1;i++)
        {
            fact=fact*i;
        }
        textbox.setText("");
        textbox.setText((textbox.getText() + fact));
       
    }//GEN-LAST:event_btnfactorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frame01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdecimal;
    private javax.swing.JButton beight;
    private javax.swing.JButton bfive;
    private javax.swing.JButton bfour;
    private javax.swing.JButton bnine;
    private javax.swing.JButton bone;
    private javax.swing.JButton bseven;
    private javax.swing.JButton bsix;
    private javax.swing.JButton bthree;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncosine;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnequals;
    private javax.swing.JButton btnexpo;
    private javax.swing.JButton btnfactorial;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnmul;
    private javax.swing.JButton btnoneby;
    private javax.swing.JButton btnsine;
    private javax.swing.JButton btnsub;
    private javax.swing.JButton btntangent;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton btnx3;
    private javax.swing.JButton btnxy;
    private javax.swing.JButton btwo;
    private javax.swing.JButton bzero;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton off;
    private javax.swing.JRadioButton on;
    private javax.swing.JTextField textbox;
    // End of variables declaration//GEN-END:variables
}
